### ISSUE TITLE
Create Project 1

### ISSUE THREAD

**Issue by Yoojin99** [Yoojin99/100-Days-of-SwiftUI-Practice#1]
# Create Project 1

## Description

Create Project 1, check-sharing app that calculates how to split a check based on the number of people and how much tip you want to leave.

정산하는 데모 앱 SwiftUI로 개발하기.

## Goal

* Lean basics of UI design
* Lean how to **let users enter values and select from options**
* Lean how to **track program state**

## TODO

* [x] Project 1, part one - Day 16
* [x] Project 1, part two - Day 17
* [x] Project 1, part three - Day 18
