### ISSUE TITLE
Create Project 2

### ISSUE THREAD

**Issue by Yoojin99** [Yoojin99/100-Days-of-SwiftUI-Practice#3]
# Create Project 2

## Description

Create Project 2, guessing game app that helps users learn some of the many flags of the world.

정산하는 데모 앱 SwiftUI로 개발하기.

## Goal

Learn

* stacks
* buttons
* images
* alerts
* asset catalogs

## TODO

* [ ] Project 2, part one - Day 20
* [ ] Project 2, part two - Day 21
* [ ] Project 2, part three - Day 22
